// This file has been autogenerated from a class added in the UI designer.

using System;
using DANFS.Services;
using Foundation;
using UIKit;

namespace DANFS.iOS
{
	public partial class ShipViewLocationTableViewController : UITableViewController
	{
		public ShipViewLocationTableViewController (IntPtr handle) : base (handle)
		{
		}

		public ShipToken Ship { get; internal set; }
	}
}
