// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using DANFS.Services;
using System.Linq;
using SQLite.Net.Interop;

namespace DANFS.iOS
{
	public partial class ShipViewController : UIViewController
	{
		public ShipViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			//this.mainTextView.Text = Ship.Title;

			RefreshWithLocations ();

		}

		async void RefreshWithLocations()
		{
			//Load all the locations for this ship.
			var dataAccess = TinyIoC.TinyIoCContainer.Current.Resolve<IDataAccess>();
			var locations = await dataAccess.GetLocationsForShip (this.Ship);
			mainTextView.Text = string.Join ("\n", locations);

			var geoLocations = await dataAccess.GetRawGeolocationsForShip (this.Ship);

			foreach (var geoLocation in geoLocations) {
				foreach (var result in geoLocation.Results) {
					var geometry = result.Geometry;
					foreach (var bound in geometry.Viewport.Values) {
						var lat = bound.Lat;
						var longitude = bound.Long;
					}
				}
			}
		}

		public IShipToken Ship {get; set;}


	}
}
